.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SWATH 1 "January 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
swath \- General-purpose Thai word segmentation utility
.SH SYNOPSIS
.B swath
[options] \<\ \fIinfile\fP\ \>\ \fIoutfile\fP
.br
.SH DESCRIPTION
Thai script has no word delimitor. Applications need some knowledge about
Thai word list to recognize word boundaries before they can do useful things
about Thai text, such as line wrapping.
.sp
Swath provides word analysis filter to insert word delimitors in a text
stream. It reads text from standard input, analyze it for word boundaries
by consulting a Thai word list, and output to standard output the same text
with the predefined word delimitors inserted.
.sp
Currently, it can read plain text, HTML, RTF, LaTeX and Lambda (Unicode version
of LaTeX with Omega typesetter kernel) documents and insert commonly used word
delimitors for each format (pipe `|' for plain text). But the user can always
override this with a preferred delimitor.
.SH OPTIONS
.TP
.B \-b [\fIdelimitor\fP]
Define a string to be used as word delimitor code in the output text.
.TP
.B \-d [\fIdict-dir\fP]
Specify alternative dictionary location. \fIdict-dir\fP must contain the swath
dictionary files `swathdic.br' and `swathdic.tl'.
.TP
.B \-f [\fIformat\fP]
Specify format of the input. Possible formats are: html, rtf, latex, lambda.
.TP
.B \-m [\fIscheme\fP]
Choose word matching scheme when analyzing word boundaries. Possible schemes
are `long' (for longest or greedy matching) and `max' (for maximal matching,
with least words preferred). Maximal matching is the default value.
.TP
.B \-u \fIinput-enc\fP,\fIoutput-enc\fP
Specify encodings of input and output. \fIinput-enc\fP and \fIoutput-enc\fP
can be one of 'u' (for UTF-8 encoding) and 't' (for TIS-620 encoding).
Swath will convert the character encoding as necessary. If omitted, TIS-620
encodings on both input and output are assumed.
.TP
.B \-v, \-\-verbose
Turn on verbose mode.
.TP
.B \-help, \-\-help
Show help.
.SH EXAMPLES
For LaTeX (to be used with thailatex package):
.sp
$ \fBswath\fP \-f latex < thaifile.tex > thaifile.ttex
.br
$ \fBlatex\fP thaifile.ttex
.sp
For HTML (to provide web pages to web browsers that cannot wrap Thai lines
properly, but support the <wbr> tag):
.sp
$ \fBswath\fP \-f html < myweb.html > myweb-wbr.html
.sp
To preprocess a Thai UTF-8 encoded LaTeX file for thailatex, which always works 
with TIS-620:
.sp
$ \fBswath\fP \-f latex \-u u,t < thaifile.tex > thaifile.ttex
.br
$ \fBlatex\fP thaifile.ttex
.sp
This is equivalent to filtering with \fBiconv(1)\fP:
.sp
$ \fBiconv\fP \-f UTF-8 \-t TIS-620 thaifile.tex | \fBswath\fP \-f latex > 
thaifile.ttex
.br
$ \fBlatex\fP thaifile.ttex
.sp
To use longest matching scheme with LaTeX document:
.sp
$ \fBswath\fP \-f latex \-m long < thaifile.tex > thaifile.ttex
.br
$ \fBlatex\fP thaifile.ttex
.SH AUTHOR
This manual page was written by Theppitak Karoonboonyanan <thep@linux.thai.net>.
